// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLkdhYugb1OBvObceKEVHzLlKBWdztDmw',
    appId: '1:328111417903:web:8c906b41ea299cbad6b4da',
    messagingSenderId: '328111417903',
    projectId: 'flutter-firebase-tutoria-c785f',
    authDomain: 'flutter-firebase-tutoria-c785f.firebaseapp.com',
    storageBucket: 'flutter-firebase-tutoria-c785f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtr0Z_b0U7Ds93pKGrz1e-18zjqcqqJEk',
    appId: '1:328111417903:android:606a8778d89df08ad6b4da',
    messagingSenderId: '328111417903',
    projectId: 'flutter-firebase-tutoria-c785f',
    storageBucket: 'flutter-firebase-tutoria-c785f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGT0fhjdwzg6lUiNYZ0C6eXKJcqP1MaWc',
    appId: '1:328111417903:ios:d7f1e61241ef8034d6b4da',
    messagingSenderId: '328111417903',
    projectId: 'flutter-firebase-tutoria-c785f',
    storageBucket: 'flutter-firebase-tutoria-c785f.appspot.com',
    iosClientId: '328111417903-bbp7ikd303jqng9c3jhs98e2fa57cllc.apps.googleusercontent.com',
    iosBundleId: 'aycabadem.flutterFirebaseTutorials',
  );
}
